name: Release
on:
  workflow_dispatch:
 
jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
    - prompt: Get prompt
      uses: fjogeleit/http-request-action@v1
      with:
    - generate: Generate
      uses:
      with: 
        url: 'https://bf.dallemini.ai/generate'
        method: 'POST'
        prompt: '{"prompt": "test"}'
        
